# {
#   "metadata": {},
#   "status": "Failure",
#   "message": "ConfigMap.core \"x.com^2\" is invalid: metadata.name: Invalid value: \"x.com^2\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
#   "reason": "Invalid",
#   "details": {
#     "name": "x.com^2",
#     "group": "core",
#     "kind": "ConfigMap",
#     "causes": [
#       {
#         "reason": "FieldValueInvalid",
#         "message": "Invalid value: \"x.com^2\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
#         "field": "metadata.name"
#       }
#     ]
#   },
#   "code": 422
# }

# Tests the kubernetes hand-coded validation for metadata fields.
# String pattern enforcement on fields like name, generateName
apiVersion: v1
kind: ConfigMap
metadata:
  name: x.com^2
data:
  key: value