# {
#     "metadata": {},
#     "status": "Failure",
#     "message": "CustomResourceDefinition.apiextensions.k8s.io \"customresourcedefinitions.apiextensions.k8s.io\" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[message].type: Unsupported value: \"strign\": supported values: \"array\", \"boolean\", \"integer\", \"number\", \"object\", \"string\"",
#     "reason": "Invalid",
#     "details": {
#         "name": "customresourcedefinitions.apiextensions.k8s.io",
#         "group": "apiextensions.k8s.io",
#         "kind": "CustomResourceDefinition",
#         "causes": [
#             {
#                 "reason": "FieldValueNotSupported",
#                 "message": "Unsupported value: \"strign\": supported values: \"array\", \"boolean\", \"integer\", \"number\", \"object\", \"string\"",
#                 "field": "spec.validation.openAPIV3Schema.properties[spec].properties[message].type"
#             }
#         ]
#     },
#     "code": 422
# }
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customresourcedefinitions.apiextensions.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: apiextensions.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: strign
                  description: a message to display
  scope: Namespaced
  names:
    plural: customresourcedefinitions
    singular: customresourcedefinitions
    kind: CustomResourceDefinition
