# {
#   "metadata": {},
#   "status": "Failure",
#   "message": "Pod.core \"my-pod\" is invalid: [<nil>: Invalid value: \"\": \"spec.containers[0].resources.requests.cpu\" must validate one and only one schema (oneOf). Found none valid, spec.containers[0].resources.requests.cpu: Invalid value: \"boolean\": spec.containers[0].resources.requests.cpu in body must be of type string: \"boolean\"]",
#   "reason": "Invalid",
#   "details": {
#     "name": "my-pod",
#     "group": "core",
#     "kind": "Pod",
#     "causes": [
#       {
#         "reason": "FieldValueInvalid",
#         "message": "Invalid value: \"\": \"spec.containers[0].resources.requests.cpu\" must validate one and only one schema (oneOf). Found none valid",
#         "field": "<nil>"
#       },
#       {
#         "reason": "FieldValueTypeInvalid",
#         "message": "Invalid value: \"boolean\": spec.containers[0].resources.requests.cpu in body must be of type string: \"boolean\"",
#         "field": "spec.containers[0].resources.requests.cpu"
#       }
#     ]
#   },
#   "code": 422
# }
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image:latest
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: true
        memory: "256Mi"