# {
#   "metadata": {},
#   "status": "Failure",
#   "message": "Internal error occurred: json: cannot unmarshal object into Go struct field ObjectMeta.finalizers of type []string",
#   "reason": "InternalError",
#   "details": {
#     "causes": [
#       {
#         "message": "json: cannot unmarshal object into Go struct field ObjectMeta.finalizers of type []string"
#       }
#     ]
#   },
#   "code": 500
# }

# Tests that "array" type is enforced when specified by openapi
# "finalizers": {
#     "description": "Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.",
#     "type": "array",
#     "items": {
#         "type": "string",
#         "default": ""
#     },
#     "x-kubernetes-patch-strategy": "merge"
# },
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-deployment
  finalizers:
    key: value
data:
  key: value