# {
#   "metadata": {},
#   "status": "Failure",
#   "message": " \"\" is invalid: spec.contAIN3rz: Invalid value: value provided for unknown field",
#   "reason": "Invalid",
#   "details": {
#     "causes": [
#       {
#         "reason": "FieldValueInvalid",
#         "message": "Invalid value: value provided for unknown field",
#         "field": "spec.contAIN3rz"
#       }
#     ]
#   },
#   "code": 422
# }
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  contAIN3rz:
    - name: nginx
      image: nginx
      ports:
        - protocol: 22
          containerPort: 88

