---
apiVersion: batch.x-k8s.io/v1alpha1
kind: JobSet
metadata:
  name: js-hostnames
spec:
  jobs:
  - name: cool-job
    network:
      enableDNSHostnames: true
    template:
      metadata:
        name: cool-job-template
      spec:
        # completionMode: Indexed
        template:
          metadata:
            name: cool-pod-template
          spec:
            containers:
            - image: nginx
              name: nginxcontainer
  